events {}

http {
	#Cabeçalhos padrão para o proxy reverso informar os dados reais da requsição ao Flask
	proxy_set_header Host $host;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header X-Forwarded-Proto $scheme;

	#Configfuração: App 1 

	server{
		listen 443 ssl;
		server_name app1.local;

		# Caminho dos certificados dentro do container do Nginx
		ssl_certificate /etc/nginx/certs/app1.local+1.pem;
		ssl_certificate_key /etc/nginx/certs/app1.local+1-key.pem;

		location / {
			proxy_pass http://app1:5000;

		}
	}
	#Redirencionamento automático de http (80) para https (443)
	server {
		listen 80;
		server_name app1.local;
		return 301 https://$host$request_uri;
	}

	#Configuração: App 2 

	server {
		listen 443 ssl;
		server_name app2.local;
		
		# Caminho dos certificados dentro do container do Nginx
		ssl_certificate /etc/nginx/certs/app1.local+1.pem;
		ssl_certificate_key /etc/nginx/certs/app1.local+1-key.pem;

		location / {
			proxy_pass http://app2:5000;
		}
	}
	#Redirencionamento automático de http (80) para https (443)
	server {
		listen 80;
		server_name app2.local;
		return 301 https://$host$request_uri;
	}
}
