services:
  localstack:
    image: localstack/localstack:3.5
    container_name: devops-journey-localstack
    ports:
      - "4566:4566"
    environment:
      SERVICES: s3,iam,sts,ec2
      DEBUG: "0"
      AWS_DEFAULT_REGION: us-east-1
      EDGE_PORT: 4566
    volumes:
      - ./tmp/localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
